//! Tauri IPC commands backing the `/` route. They delegate to a
//! per-session [`mesh_talk_core::node::NodeRuntime`] held in managed [`NodeState`] (populated on
//! login, cleared on logout). All are thin pass-throughs over the node API.

use crate::commands::CommandError;
use mesh_talk_core::eventlog::event::{ConversationId, EventId};

mod account;
mod channels;
mod diagnostics;
mod files;
mod messaging;
mod models;
mod platform;
mod state;

#[cfg(test)]
use diagnostics::{presence_from_seen, PRESENCE_TTL_SECS};
#[cfg(test)]
use files::temp_file_basename;

// Glob re-exports also forward the private command macros generated by Tauri.
pub use account::*;
pub use channels::*;
pub use diagnostics::*;
pub use files::*;
pub use messaging::*;
pub use models::*;
pub use platform::*;
pub use state::NodeState;
pub(crate) use state::RuntimeAuthority;

fn parse_channel_id(hex_id: &str) -> Result<ConversationId, CommandError> {
    let bytes =
        hex::decode(hex_id).map_err(|_| CommandError::Validation("invalid channel id".into()))?;
    let arr: [u8; 32] = bytes
        .try_into()
        .map_err(|_| CommandError::Validation("channel id must be 32 bytes".into()))?;
    Ok(ConversationId::new(arr))
}

fn parse_event_id(hex_id: &str) -> Result<EventId, CommandError> {
    let bytes =
        hex::decode(hex_id).map_err(|_| CommandError::Validation("invalid event id".into()))?;
    let arr: [u8; 32] = bytes
        .try_into()
        .map_err(|_| CommandError::Validation("event id must be 32 bytes".into()))?;
    Ok(EventId::new(arr))
}

fn to_reaction_infos(views: Vec<mesh_talk_core::node::ReactionView>) -> Vec<ReactionInfo> {
    views
        .into_iter()
        .map(|v| ReactionInfo {
            target: v.target,
            emoji: v.emoji,
            who: v.who,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn temp_file_keeps_real_filename_and_extension() {
        // The "send image/video" picker passes the real name: it must survive verbatim, so
        // a .mov stays a previewable .mov — NOT a MIME-derived `pasted-….quicktim`.
        let mov = "Screen Recording 2026-03-16 at 17.41.43.mov";
        assert_eq!(
            temp_file_basename("quicktime", Some(mov), 1782196051325),
            mov
        );
        // A path component is never trusted — only the basename is kept (no traversal).
        assert_eq!(
            temp_file_basename("png", Some("../../etc/passwd"), 1),
            "passwd"
        );
    }

    #[test]
    fn temp_file_synthesizes_name_for_nameless_clipboard_bytes() {
        // No real name (a pasted screenshot) → synthesize, sanitizing the ext.
        assert_eq!(temp_file_basename("png", None, 42), "pasted-42.png");
        assert_eq!(temp_file_basename("", None, 42), "pasted-42.png");
        // Degenerate names fall back to the synthetic form, not an empty/dotfile path.
        assert_eq!(temp_file_basename("png", Some(".."), 42), "pasted-42.png");
        assert_eq!(temp_file_basename("png", Some("   "), 42), "pasted-42.png");
    }

    #[test]
    fn parse_channel_id_accepts_64_hex_chars() {
        let id = parse_channel_id(&"ab".repeat(32)).expect("valid id");
        assert_eq!(id.as_bytes(), &[0xab; 32]);
    }

    #[test]
    fn parse_channel_id_rejects_wrong_length() {
        assert!(parse_channel_id(&"ab".repeat(16)).is_err()); // 16 bytes, not 32
        assert!(parse_channel_id("").is_err());
    }

    #[test]
    fn parse_channel_id_rejects_non_hex() {
        assert!(parse_channel_id(&"zz".repeat(32)).is_err()); // not hex
        assert!(parse_channel_id("abc").is_err()); // odd-length hex
    }

    #[test]
    fn parse_event_id_accepts_valid_and_rejects_bad_input() {
        assert_eq!(
            parse_event_id(&"cd".repeat(32)).expect("valid").as_bytes(),
            &[0xcd; 32]
        );
        assert!(parse_event_id(&"cd".repeat(10)).is_err()); // too short
        assert!(parse_event_id(&"gg".repeat(32)).is_err()); // not hex
    }

    #[test]
    fn presence_fresh_device_is_online() {
        let p = presence_from_seen([5u64].into_iter());
        assert!(p.online);
        assert_eq!(p.last_seen_secs, Some(5));
    }

    #[test]
    fn presence_all_stale_is_offline_with_freshest_last_seen() {
        let p = presence_from_seen([60u64, 45, 90].into_iter());
        assert!(!p.online);
        assert_eq!(p.last_seen_secs, Some(45)); // freshest (min), still > TTL
    }

    #[test]
    fn presence_empty_is_offline_never_seen() {
        let p = presence_from_seen(std::iter::empty());
        assert!(!p.online);
        assert_eq!(p.last_seen_secs, None);
    }

    #[test]
    fn presence_uses_freshest_of_many_devices() {
        // One fresh device among stale ones makes the conversation online,
        // and last_seen reflects the freshest (min).
        let p = presence_from_seen([100u64, 3, 50].into_iter());
        assert!(p.online);
        assert_eq!(p.last_seen_secs, Some(3));
    }

    #[test]
    fn presence_ttl_boundary_is_strict() {
        // Exactly TTL is offline (strict `<`); one second under is online.
        let at = presence_from_seen([PRESENCE_TTL_SECS].into_iter());
        assert!(!at.online);
        assert_eq!(at.last_seen_secs, Some(PRESENCE_TTL_SECS));

        let under = presence_from_seen([PRESENCE_TTL_SECS - 1].into_iter());
        assert!(under.online);
        assert_eq!(under.last_seen_secs, Some(PRESENCE_TTL_SECS - 1));
    }
}
